// Code generated by internal/tools/cmd/ecode. DO NOT EDIT.
package xerrors

var ErrE0001 = newEcode("E0001", `sheet not found in book`)
var ErrE0002 = newEcode("E0002", `cannot unmarshal file content to given proto.Message`)
var ErrE0003 = newEcode("E0003", `duplicate column name`)
var ErrE2000 = newEcode("E2000", `integer overflow`)
var ErrE2001 = newEcode("E2001", `field prop "refer" not configured correctly`)
var ErrE2002 = newEcode("E2002", `field value not in referred space`)
var ErrE2003 = newEcode("E2003", `illegal sequence number`)
var ErrE2004 = newEcode("E2004", `value is out of range`)
var ErrE2005 = newEcode("E2005", `map or keyed-list key not unique`)
var ErrE2006 = newEcode("E2006", `enum value not defined in enum type`)
var ErrE2007 = newEcode("E2007", `invalid datetime format`)
var ErrE2008 = newEcode("E2008", `invalid duration format`)
var ErrE2009 = newEcode("E2009", `duplicate key exists in different sheets`)
var ErrE2010 = newEcode("E2010", `union type has no corresponding value field`)
var ErrE2011 = newEcode("E2011", `field presence required but cell not filled`)
var ErrE2012 = newEcode("E2012", `invalid syntax of numerical value`)
var ErrE2013 = newEcode("E2013", `invalid syntax of boolean value`)
var ErrE2014 = newEcode("E2014", `sheet column not found`)
var ErrE2015 = newEcode("E2015", `referred sheet column not found`)
var ErrE2016 = newEcode("E2016", `list elements are not present continuously`)
var ErrE2017 = newEcode("E2017", `map contains multiple empty keys`)
var ErrE2018 = newEcode("E2018", `map key not exists`)
var ErrE2019 = newEcode("E2019", `invalid fraction pattern`)
var ErrE2020 = newEcode("E2020", `invalid comparator pattern`)
var ErrE2021 = newEcode("E2021", `duplicate enum value alias`)
var ErrE2022 = newEcode("E2022", `sub-field's value not unique in map values or list elements`)
var ErrE2024 = newEcode("E2024", `invalid version pattern`)
var ErrE2025 = newEcode("E2025", `version value mismatches pattern`)
var ErrE2026 = newEcode("E2026", `illegally ordered number`)
var ErrE3000 = newEcode("E3000", `no workbook file found about sheet specifier`)
var ErrE3001 = newEcode("E3001", `no worksheet found in workbook`)
var ErrE3002 = newEcode("E3002", `failed to open file`)
var ErrE3003 = newEcode("E3003", `CSV workbook glob pattern matches no files`)

// E0001: sheet not found in book
func E0001(sheetName string, bookName string) error {
	return renderEcode(ErrE0001, map[string]any{
		"SheetName": sheetName,
		"BookName":  bookName,
	})
}

// E0002: cannot unmarshal file content to given proto.Message
func E0002(filename string, messageName string, error_ error, lines string) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE0002, map[string]any{
		"Filename":    filename,
		"MessageName": messageName,
		"Error":       error_,
		"Lines":       lines,
	})
}

// E0003: duplicate column name
func E0003(name string, position1 string, position2 string) error {
	return renderEcode(ErrE0003, map[string]any{
		"Name":      name,
		"Position1": position1,
		"Position2": position2,
	})
}

// E2000: integer overflow
func E2000(type_ string, value string, min any, max any) error {
	return renderEcode(ErrE2000, map[string]any{
		"Type":  type_,
		"Value": value,
		"Min":   min,
		"Max":   max,
	})
}

// E2001: field prop "refer" not configured correctly
func E2001(refer string, messageName string) error {
	return renderEcode(ErrE2001, map[string]any{
		"Refer":       refer,
		"MessageName": messageName,
	})
}

// E2002: field value not in referred space
func E2002(value string, refer string) error {
	return renderEcode(ErrE2002, map[string]any{
		"Value": value,
		"Refer": refer,
	})
}

// E2003: illegal sequence number
func E2003(value string, sequence int64) error {
	return renderEcode(ErrE2003, map[string]any{
		"Value":    value,
		"Sequence": sequence,
	})
}

// E2004: value is out of range
func E2004(value any, range_ string) error {
	return renderEcode(ErrE2004, map[string]any{
		"Value": value,
		"Range": range_,
	})
}

// E2005: map or keyed-list key not unique
func E2005(key any) error {
	return renderEcode(ErrE2005, map[string]any{
		"Key": key,
	})
}

// E2006: enum value not defined in enum type
func E2006(value any, enumName any) error {
	return renderEcode(ErrE2006, map[string]any{
		"Value":    value,
		"EnumName": enumName,
	})
}

// E2007: invalid datetime format
func E2007(value any, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2007, map[string]any{
		"Value": value,
		"Error": error_,
	})
}

// E2008: invalid duration format
func E2008(value any, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2008, map[string]any{
		"Value": value,
		"Error": error_,
	})
}

// E2009: duplicate key exists in different sheets
func E2009(key any, fieldName string) error {
	return renderEcode(ErrE2009, map[string]any{
		"Key":       key,
		"FieldName": fieldName,
	})
}

// E2010: union type has no corresponding value field
func E2010(typeValue any, fieldNumber any) error {
	return renderEcode(ErrE2010, map[string]any{
		"TypeValue":   typeValue,
		"FieldNumber": fieldNumber,
	})
}

// E2011: field presence required but cell not filled
func E2011() error {
	return renderEcode(ErrE2011, map[string]any{})
}

// E2012: invalid syntax of numerical value
func E2012(fieldType any, value any, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2012, map[string]any{
		"FieldType": fieldType,
		"Value":     value,
		"Error":     error_,
	})
}

// E2013: invalid syntax of boolean value
func E2013(value any, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2013, map[string]any{
		"Value": value,
		"Error": error_,
	})
}

// E2014: sheet column not found
func E2014(column string) error {
	return renderEcode(ErrE2014, map[string]any{
		"Column": column,
	})
}

// E2015: referred sheet column not found
func E2015(column string, bookName string, sheetName string) error {
	return renderEcode(ErrE2015, map[string]any{
		"Column":    column,
		"BookName":  bookName,
		"SheetName": sheetName,
	})
}

// E2016: list elements are not present continuously
func E2016(firstNonePresentIndex int, nextPresentIndex int) error {
	return renderEcode(ErrE2016, map[string]any{
		"FirstNonePresentIndex": firstNonePresentIndex,
		"NextPresentIndex":      nextPresentIndex,
	})
}

// E2017: map contains multiple empty keys
func E2017(mapType string) error {
	return renderEcode(ErrE2017, map[string]any{
		"MapType": mapType,
	})
}

// E2018: map key not exists
func E2018(keyName string) error {
	return renderEcode(ErrE2018, map[string]any{
		"KeyName": keyName,
	})
}

// E2019: invalid fraction pattern
func E2019(value string, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2019, map[string]any{
		"Value": value,
		"Error": error_,
	})
}

// E2020: invalid comparator pattern
func E2020(value string, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2020, map[string]any{
		"Value": value,
		"Error": error_,
	})
}

// E2021: duplicate enum value alias
func E2021(enumType any, enumValue1 any, enumValue2 any, alias any) error {
	return renderEcode(ErrE2021, map[string]any{
		"EnumType":   enumType,
		"EnumValue1": enumValue1,
		"EnumValue2": enumValue2,
		"Alias":      alias,
	})
}

// E2022: sub-field's value not unique in map values or list elements
func E2022(fieldName string, key any) error {
	return renderEcode(ErrE2022, map[string]any{
		"FieldName": fieldName,
		"Key":       key,
	})
}

// E2024: invalid version pattern
func E2024(value string, error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE2024, map[string]any{
		"Value": value,
		"Error": error_,
	})
}

// E2025: version value mismatches pattern
func E2025(value string, pattern string) error {
	return renderEcode(ErrE2025, map[string]any{
		"Value":   value,
		"Pattern": pattern,
	})
}

// E2026: illegally ordered number
func E2026(value any, prevValue any, order string) error {
	return renderEcode(ErrE2026, map[string]any{
		"Value":     value,
		"PrevValue": prevValue,
		"Order":     order,
	})
}

// E3000: no workbook file found about sheet specifier
func E3000(sheetSpecifier string, pattern string) error {
	return renderEcode(ErrE3000, map[string]any{
		"SheetSpecifier": sheetSpecifier,
		"Pattern":        pattern,
	})
}

// E3001: no worksheet found in workbook
func E3001(sheetName string, bookName string) error {
	return renderEcode(ErrE3001, map[string]any{
		"SheetName": sheetName,
		"BookName":  bookName,
	})
}

// E3002: failed to open file
func E3002(error_ error) error {
	if error_ == nil {
		return nil
	}
	return renderEcode(ErrE3002, map[string]any{
		"Error": error_,
	})
}

// E3003: CSV workbook glob pattern matches no files
func E3003(glob string) error {
	return renderEcode(ErrE3003, map[string]any{
		"Glob": glob,
	})
}
