coverage:
  status:
    project:
      default:
        target: 55%
        threshold: 1%
ignore:
    - "**/*.pb.go" # ignore all *.pb.go files
    - "test" # ignore folders and all its contents
