coverage:
  status:
    project:
      default:
        target: 63%
        threshold: 1%
ignore:
  - "**/*.pb.go" # ignore all *.pb.go files
  - "**/*_generated.go"
  - "test" # ignore folders and all its contents
  - "internal/tools"
