package protoc

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/tableauio/tableau/proto/tableaupb"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	testUnittestProtoPath = "tableau/protobuf/unittest/unittest.proto"
	testCommonProtoPath   = "tableau/protobuf/unittest/common.proto"
)

// genDescriptorSet compiles the unittest protos and writes them into a
// descriptor set file, mimicking what an external compiler does with
// `protoc --include_imports --descriptor_set_out`. Only the given proto paths
// are written if specified, so as to simulate an incomplete descriptor set.
func genDescriptorSet(t *testing.T, onlyProtoPaths ...string) string {
	t.Helper()
	files, err := NewFiles(
		[]string{"../../../../proto"},
		[]string{"../../../../proto/tableau/protobuf/unittest/*.proto"},
	)
	require.NoError(t, err)

	wanted := make(map[string]bool, len(onlyProtoPaths))
	for _, protoPath := range onlyProtoPaths {
		wanted[protoPath] = true
	}
	fds := &descriptorpb.FileDescriptorSet{}
	files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		if len(wanted) == 0 || wanted[fd.Path()] {
			fds.File = append(fds.File, protodesc.ToFileDescriptorProto(fd))
		}
		return true
	})
	return writeDescriptorSet(t, fds)
}

func writeDescriptorSet(t *testing.T, fds *descriptorpb.FileDescriptorSet) string {
	t.Helper()
	data, err := proto.Marshal(fds)
	require.NoError(t, err)
	path := filepath.Join(t.TempDir(), "unittest.binpb")
	require.NoError(t, os.WriteFile(path, data, 0o644))
	return path
}

const (
	// testPredefinedProto is a handwritten proto file serving as common types,
	// which has no workbook option.
	testPredefinedProto = `syntax = "proto3";
package dstest;
message CommonItem { uint32 id = 1; }
`
	// testGeneratedProto mimics a proto file previously generated by protogen,
	// which always has the file-level workbook option.
	testGeneratedProto = `syntax = "proto3";
package dstest;
import "tableau/protobuf/tableau.proto";
import "predefined.proto";
option (tableau.workbook) = {name:"Item#*.csv" namerow:1 typerow:2 datarow:3};
message ItemConf {
  option (tableau.worksheet) = {name:"ItemConf"};
  CommonItem item = 1;
}
`
	// testBadPredefinedProto violates the contract: a predefined proto file
	// must not import a generated one.
	testBadPredefinedProto = `syntax = "proto3";
package dstest;
import "generated.proto";
message BadItem { ItemConf conf = 1; }
`
)

// genDescriptorSetFromSources compiles the given proto sources, keyed by proto
// path, and writes them into a descriptor set file.
func genDescriptorSetFromSources(t *testing.T, sources map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range sources {
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644))
	}
	files, err := NewFiles(
		[]string{dir, "../../../../proto"},
		[]string{filepath.Join(dir, "*.proto")},
	)
	require.NoError(t, err)
	fds := &descriptorpb.FileDescriptorSet{}
	files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		fds.File = append(fds.File, protodesc.ToFileDescriptorProto(fd))
		return true
	})
	return writeDescriptorSet(t, fds)
}

func TestNewPredefinedFilesFromDescriptorSet(t *testing.T) {
	t.Run("exclude generated proto files", func(t *testing.T) {
		descriptorSetFile := genDescriptorSetFromSources(t, map[string]string{
			"predefined.proto": testPredefinedProto,
			"generated.proto":  testGeneratedProto,
		})

		files, err := NewPredefinedFilesFromDescriptorSet(descriptorSetFile)
		require.NoError(t, err)
		_, err = files.FindFileByPath("predefined.proto")
		assert.NoError(t, err, "predefined proto file should be kept")
		_, err = files.FindFileByPath("generated.proto")
		assert.Error(t, err, "generated proto file should be excluded")
		_, err = files.FindDescriptorByName("dstest.ItemConf")
		assert.Error(t, err, "message in generated proto file should not be found")
		_, err = files.FindDescriptorByName("dstest.CommonItem")
		assert.NoError(t, err)

		// while all of them are kept by NewFilesFromDescriptorSet
		allFiles, err := NewFilesFromDescriptorSet(descriptorSetFile)
		require.NoError(t, err)
		for _, protoPath := range []string{"predefined.proto", "generated.proto"} {
			_, err = allFiles.FindFileByPath(protoPath)
			assert.NoError(t, err, "proto file %s should be kept", protoPath)
		}
	})

	t.Run("predefined proto file importing generated one is rejected", func(t *testing.T) {
		descriptorSetFile := genDescriptorSetFromSources(t, map[string]string{
			"predefined.proto":     testPredefinedProto,
			"generated.proto":      testGeneratedProto,
			"bad_predefined.proto": testBadPredefinedProto,
		})

		// the whole descriptor set is valid
		_, err := NewFilesFromDescriptorSet(descriptorSetFile)
		require.NoError(t, err)

		_, err = NewPredefinedFilesFromDescriptorSet(descriptorSetFile)
		require.Error(t, err)
		assert.ErrorContains(t, err, "must not import the generated ones")
		assert.ErrorContains(t, err, "generated.proto")
	})

	t.Run("all proto files are generated", func(t *testing.T) {
		descriptorSetFile := genDescriptorSetFromSources(t, map[string]string{
			"generated.proto": `syntax = "proto3";
package dstest;
import "tableau/protobuf/tableau.proto";
option (tableau.workbook) = {name:"Item#*.csv" namerow:1 typerow:2 datarow:3};
message ItemConf {
  option (tableau.worksheet) = {name:"ItemConf"};
  uint32 id = 1;
}
`,
		})

		// no predefined proto file is not an error
		files, err := NewPredefinedFilesFromDescriptorSet(descriptorSetFile)
		require.NoError(t, err)
		_, err = files.FindDescriptorByName("dstest.ItemConf")
		assert.Error(t, err)
	})

	t.Run("descriptor set file not found", func(t *testing.T) {
		_, err := NewPredefinedFilesFromDescriptorSet("not-existed.binpb")
		assert.ErrorContains(t, err, "failed to read descriptor set file")
	})
}

func TestNewFilesFromDescriptorSet(t *testing.T) {
	t.Run("load all proto files", func(t *testing.T) {
		files, err := NewFilesFromDescriptorSet(genDescriptorSet(t))
		require.NoError(t, err)
		for _, protoPath := range []string{testUnittestProtoPath, testCommonProtoPath} {
			_, err := files.FindFileByPath(protoPath)
			assert.NoError(t, err, "proto file %s not found", protoPath)
		}
		// imports should be loaded as well
		_, err = files.FindFileByPath("google/protobuf/timestamp.proto")
		assert.NoError(t, err)
		_, err = files.FindDescriptorByName("unittest.FruitType")
		assert.NoError(t, err)
	})

	t.Run("custom options are statically typed", func(t *testing.T) {
		files, err := NewFilesFromDescriptorSet(genDescriptorSet(t))
		require.NoError(t, err)
		fd, err := files.FindFileByPath(testUnittestProtoPath)
		require.NoError(t, err)
		fileOpts, ok := fd.Options().(*descriptorpb.FileOptions)
		require.True(t, ok)
		bookOpts, ok := proto.GetExtension(fileOpts, tableaupb.E_Workbook).(*tableaupb.WorkbookOptions)
		require.True(t, ok)
		assert.Equal(t, "unittest/Unittest#*.csv", bookOpts.GetName())
	})

	t.Run("all imports are resolved", func(t *testing.T) {
		files, err := NewFilesFromDescriptorSet(genDescriptorSet(t))
		require.NoError(t, err)
		files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
			for i := 0; i < fd.Imports().Len(); i++ {
				imp := fd.Imports().Get(i)
				assert.False(t, imp.IsPlaceholder(), "import %s of %s is unresolved", imp.Path(), fd.Path())
			}
			return true
		})
	})

	t.Run("import not included in descriptor set", func(t *testing.T) {
		// NOTE: even the proto files already linked into the current binary
		// must be included in the descriptor set.
		partialFile := genDescriptorSet(t, testUnittestProtoPath, testCommonProtoPath)
		_, err := NewFilesFromDescriptorSet(partialFile)
		require.ErrorContains(t, err, "--include_imports")
		assert.ErrorContains(t, err, "tableau/protobuf/tableau.proto")
	})

	t.Run("descriptor set file not found", func(t *testing.T) {
		_, err := NewFilesFromDescriptorSet("not-existed.binpb")
		assert.ErrorContains(t, err, "failed to read descriptor set file")
	})

	t.Run("invalid descriptor set file", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "invalid.binpb")
		require.NoError(t, os.WriteFile(path, []byte("not a descriptor set"), 0o644))
		_, err := NewFilesFromDescriptorSet(path)
		assert.ErrorContains(t, err, "failed to unmarshal descriptor set file")
	})

	t.Run("empty descriptor set file", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "empty.binpb")
		require.NoError(t, os.WriteFile(path, nil, 0o644))
		_, err := NewFilesFromDescriptorSet(path)
		assert.ErrorContains(t, err, "no proto file found")
	})

	t.Run("duplicate proto file in descriptor set", func(t *testing.T) {
		fdp := &descriptorpb.FileDescriptorProto{
			Name:   proto.String("foo.proto"),
			Syntax: proto.String("proto3"),
		}
		fds := &descriptorpb.FileDescriptorSet{
			File: []*descriptorpb.FileDescriptorProto{fdp, fdp},
		}
		_, err := NewFilesFromDescriptorSet(writeDescriptorSet(t, fds))
		assert.ErrorContains(t, err, "appears multiple times")
	})
}
