package protoc

import (
	"os"

	"github.com/tableauio/tableau/internal/x/xerrors"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

// NewFilesFromDescriptorSet creates a new protoregistry.Files from the given
// pre-compiled descriptor set file, rather than compiling proto source files
// at runtime.
//
// A descriptor set file stores a serialized descriptorpb.FileDescriptorSet,
// which can be generated by any external protobuf compiler, e.g.:
//
//	protoc -I<proto path> --include_imports --descriptor_set_out=<out file> <proto files>...
//	buf build -o <out file>
//
// This is the counterpart of protoc's --descriptor_set_in flag, which makes
// tableau independent of the proto language versions (editions) supported by
// the builtin compiler.
//
// NOTE: the descriptor set is the only source of truth here. It must be
// self-contained, aka generated with --include_imports, even for the proto
// files already linked into the current binary.
func NewFilesFromDescriptorSet(descriptorSetFile string) (*protoregistry.Files, error) {
	data, err := os.ReadFile(descriptorSetFile)
	if err != nil {
		return nil, xerrors.Wrapf(err, "failed to read descriptor set file: %s", descriptorSetFile)
	}
	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(data, fds); err != nil {
		return nil, xerrors.Wrapf(err, "failed to unmarshal descriptor set file: %s", descriptorSetFile)
	}
	if len(fds.GetFile()) == 0 {
		return nil, xerrors.Newf("no proto file found in descriptor set file: %s", descriptorSetFile)
	}
	// NOTE: protodesc.NewFiles takes care of the creation order (imports are
	// always created before importers), import cycles, duplicate files and
	// unresolvable imports, so the file descriptor protos can be fed in as a
	// whole.
	files, err := protodesc.NewFiles(fds)
	if err != nil {
		return nil, xerrors.Wrapf(err, "invalid descriptor set file %s: it should be generated with --include_imports", descriptorSetFile)
	}
	return files, nil
}
