package protoc

import (
	"os"

	"github.com/tableauio/tableau/internal/x/xerrors"
	"github.com/tableauio/tableau/log"
	"github.com/tableauio/tableau/proto/tableaupb"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

// NewFilesFromDescriptorSet creates a new protoregistry.Files from all proto
// files in the given pre-compiled descriptor set file, rather than compiling
// proto source files at runtime.
//
// A descriptor set file stores a serialized descriptorpb.FileDescriptorSet,
// which can be generated by any external protobuf compiler, e.g.:
//
//	protoc -I<proto path> --include_imports --descriptor_set_out=<out file> <proto files>...
//	buf build -o <out file>
//
// This is the counterpart of protoc's --descriptor_set_in flag, which makes
// tableau independent of the proto language versions (editions) supported by
// the builtin compiler.
//
// NOTE: the descriptor set is the only source of truth here. It must be
// self-contained, aka generated with --include_imports, even for the proto
// files already linked into the current binary.
func NewFilesFromDescriptorSet(descriptorSetFile string) (*protoregistry.Files, error) {
	fds, err := loadDescriptorSet(descriptorSetFile)
	if err != nil {
		return nil, err
	}
	// NOTE: protodesc.NewFiles takes care of the creation order (imports are
	// always created before importers), import cycles, duplicate files and
	// unresolvable imports, so the file descriptor protos can be fed in as a
	// whole.
	files, err := protodesc.NewFiles(fds)
	if err != nil {
		return nil, xerrors.Wrapf(err, "invalid descriptor set file %s: it should be generated with --include_imports", descriptorSetFile)
	}
	return files, nil
}

// NewPredefinedFilesFromDescriptorSet is the same as NewFilesFromDescriptorSet,
// except that the proto files previously generated by protogen are excluded, so
// as to keep only the predefined ones.
//
// In descriptor set mode, the proto paths are lost, so the generated proto files
// can no longer be told apart by the output dir as in proto source file mode.
// They are identified by the file-level (tableau.workbook) option instead, which
// protogen always generates for each proto file. Therefore the predefined proto
// files, which serve as the common types of workbooks, must not have this
// option.
//
// An error is reported if one predefined proto file imports a generated one, as
// the predefined ones should never depend on the generated ones.
func NewPredefinedFilesFromDescriptorSet(descriptorSetFile string) (*protoregistry.Files, error) {
	fds, err := loadDescriptorSet(descriptorSetFile)
	if err != nil {
		return nil, err
	}
	predefined := &descriptorpb.FileDescriptorSet{
		File: make([]*descriptorpb.FileDescriptorProto, 0, len(fds.GetFile())),
	}
	var generated []string
	for _, fdp := range fds.GetFile() {
		if isGeneratedProto(fdp) {
			generated = append(generated, fdp.GetName())
			continue
		}
		predefined.File = append(predefined.File, fdp)
	}
	log.Debugf("exclude generated proto files in descriptor set: %v", generated)
	// NOTE: rebuild the registry from the remaining file descriptor protos,
	// rather than filtering the built one, as the imports of a file descriptor
	// are direct references instead of registry lookups, which means the
	// excluded files would still be reachable. Rebuilding makes protodesc
	// reject a predefined proto file importing a generated one, just as
	// compiling proto source files does.
	files, err := protodesc.NewFiles(predefined)
	if err != nil {
		return nil, xerrors.Wrapf(err, "invalid descriptor set file %s: the predefined proto files, aka those without the (tableau.workbook) option, should be self-contained and must not import the generated ones: %v", descriptorSetFile, generated)
	}
	return files, nil
}

func loadDescriptorSet(descriptorSetFile string) (*descriptorpb.FileDescriptorSet, error) {
	data, err := os.ReadFile(descriptorSetFile)
	if err != nil {
		return nil, xerrors.Wrapf(err, "failed to read descriptor set file: %s", descriptorSetFile)
	}
	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(data, fds); err != nil {
		return nil, xerrors.Wrapf(err, "failed to unmarshal descriptor set file: %s", descriptorSetFile)
	}
	if len(fds.GetFile()) == 0 {
		return nil, xerrors.Newf("no proto file found in descriptor set file: %s", descriptorSetFile)
	}
	return fds, nil
}

// isGeneratedProto reports whether the given proto file was generated by
// protogen, which always generates the file-level (tableau.workbook) option.
func isGeneratedProto(fdp *descriptorpb.FileDescriptorProto) bool {
	opts := fdp.GetOptions()
	if opts == nil {
		return false
	}
	return proto.HasExtension(opts, tableaupb.E_Workbook)
}
