package protogen

import (
	"path/filepath"
	"regexp"
	"strings"

	"github.com/emirpasic/gods/sets/treeset"
	"github.com/rogpeppe/go-internal/lockedfile"
	"github.com/tableauio/tableau/internal/printer"
	"github.com/tableauio/tableau/internal/strcase"
	"github.com/tableauio/tableau/internal/types"
	"github.com/tableauio/tableau/internal/x/xfs"
	"github.com/tableauio/tableau/internal/x/xproto"
	"github.com/tableauio/tableau/log"
	"github.com/tableauio/tableau/proto/tableaupb"
	"github.com/tableauio/tableau/proto/tableaupb/internalpb"
	"github.com/tableauio/tableau/xerrors"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type bookExporter struct {
	ProtoPackage     string
	ProtoFileOptions map[string]string
	OutputDir        string
	FilenameSuffix   string
	wb               *internalpb.Workbook

	gen *Generator

	messagerPatternRegexp *regexp.Regexp
}

func newBookExporter(protoPackage string, protoFileOptions map[string]string, outputDir, filenameSuffix string, wb *internalpb.Workbook, gen *Generator) *bookExporter {
	return &bookExporter{
		ProtoPackage:          protoPackage,
		ProtoFileOptions:      protoFileOptions,
		OutputDir:             outputDir,
		FilenameSuffix:        filenameSuffix,
		wb:                    wb,
		gen:                   gen,
		messagerPatternRegexp: regexp.MustCompile(gen.InputOpt.MessagerPattern),
	}
}

func (x *bookExporter) GetProtoFilePath() string {
	return genProtoFilePath(x.wb.GetName(), x.FilenameSuffix)
}

func (x *bookExporter) export(checkProtoFileConflicts bool) error {
	// log.Debug(proto.MarshalTextString(wb))
	p1 := printer.New()
	p1.P("// Code generated by tableau (protogen v", Version, "). DO NOT EDIT.")
	p1.P("// clang-format off")
	p1.P("")
	p1.P(`syntax = "proto3";`)
	p1.P("")
	p1.P("package ", x.ProtoPackage, ";")
	p1.P("")

	// keep the elements ordered by import path
	set := treeset.NewWithStringComparator()
	set.Add(tableauProtoPath) // default must be imported path
	p3 := printer.New()
	for i, ws := range x.wb.Worksheets {
		se := &sheetExporter{
			be:             x,
			ws:             ws,
			p:              p3,
			isLastSheet:    i == len(x.wb.Worksheets)-1,
			typeInfos:      x.gen.typeInfos,
			nestedMessages: make(map[string]*internalpb.Field),
			Imports:        make(map[string]bool),
		}
		if err := se.export(); err != nil {
			return xerrors.WrapKV(err, xerrors.KeySheetName, ws.Name)
		}
		for key := range se.Imports {
			set.Add(key)
		}
	}

	// generate imports
	p2 := printer.New()
	for _, key := range set.Values() {
		p2.P(`import "`, key, `";`)
	}
	p2.P("")
	for k, v := range x.ProtoFileOptions {
		p2.P(`option `, k, ` = "`, v, `";`)
	}
	p2.P("option (tableau.workbook) = {", marshalToText(x.wb.Options), "};")
	p2.P("")

	relPath := x.GetProtoFilePath()
	path := filepath.Join(x.OutputDir, relPath)
	log.Infof("%15s: %s", "generated proto", relPath)

	// mu := lockedfile.MutexAt(path)
	// unlock, err := mu.Lock()
	// if err != nil {
	// 	return xerrors.Wrapf(err, "failed to lock file: %s", path)
	// }
	// defer unlock()

	// NOTE: use file lock to protect .proto file from being written concurrently by multiple goroutines
	// refer: https://github.com/golang/go/issues/33974
	// refer: https://go.googlesource.com/proposal/+/master/design/33974-add-public-lockedfile-pkg.md

	if checkProtoFileConflicts {
		if existed, err := xfs.Exists(path); err != nil {
			return xerrors.WrapKV(err)
		} else {
			if existed {
				return xerrors.Newf("file already exists: %s", path)
			}
		}
	}

	if f, err := lockedfile.Create(path); err != nil {
		return xerrors.WrapKV(err)
	} else {
		defer func() {
			err := f.Close()
			if err != nil {
				log.Panicf("failed to close file: %s", path)
			}
		}()
		if _, err = f.Write(p1.Bytes()); err != nil {
			return xerrors.WrapKV(err)
		}
		if _, err = f.Write(p2.Bytes()); err != nil {
			return xerrors.WrapKV(err)
		}
		if _, err = f.Write(p3.Bytes()); err != nil {
			return xerrors.WrapKV(err)
		}
	}

	return nil
}

type sheetExporter struct {
	be          *bookExporter
	ws          *internalpb.Worksheet
	p           *printer.Printer
	isLastSheet bool
	typeInfos   *xproto.TypeInfos

	Imports        map[string]bool              // import name -> defined
	nestedMessages map[string]*internalpb.Field // top message scoped type name -> field
}

func (x *sheetExporter) export() error {
	mode := x.ws.GetOptions().GetMode()
	switch x.ws.Options.Mode {
	case tableaupb.Mode_MODE_DEFAULT:
		return x.exportMessager()
	case tableaupb.Mode_MODE_ENUM_TYPE, tableaupb.Mode_MODE_ENUM_TYPE_MULTI:
		return x.exportEnum()
	case tableaupb.Mode_MODE_STRUCT_TYPE, tableaupb.Mode_MODE_STRUCT_TYPE_MULTI:
		return x.exportStruct()
	case tableaupb.Mode_MODE_UNION_TYPE, tableaupb.Mode_MODE_UNION_TYPE_MULTI:
		return x.exportUnion()
	default:
		return xerrors.Newf("unknown mode: %v", mode)
	}
}

func (x *sheetExporter) exportEnum() error {
	if x.ws.Note != "" {
		x.p.P("// ", x.ws.Note)
	}
	x.p.P("enum ", x.ws.Name, " {")
	opts := &tableaupb.EnumOptions{Name: x.ws.GetOptions().GetName(), Note: x.ws.Note}
	x.p.P("  option (tableau.etype) = {", marshalToText(opts), "};")
	x.p.P("")
	// generate the enum value fields
	for i, field := range x.ws.Fields {
		if i == 0 && field.Number != 0 {
			ename := strcase.FromContext(x.be.gen.ctx).ToScreamingSnake(x.ws.Name) + "_INVALID"
			x.p.P("  ", ename, " = 0;")
		}
		if field.Number == 0 && i != 0 {
			return xerrors.Newf("zero enum value must be the first one, but found at enum value row: %d", i+1)
		}
		note := ""
		if field.Alias != "" {
			note = " // " + field.Alias
		}
		x.p.P("  ", strings.TrimSpace(field.Name), " = ", field.Number, ` [(tableau.evalue).name = "`, strings.TrimSpace(field.Alias), `"];`, note)
	}
	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

func (x *sheetExporter) exportStruct() error {
	x.p.P("message ", x.ws.Name, " {")
	opts := &tableaupb.StructOptions{Name: x.ws.GetOptions().GetName(), Note: x.ws.Note}
	x.p.P("  option (tableau.struct) = {", marshalToText(opts), "};")
	x.p.P("")
	// generate the fields
	depth := 1
	tagid := int32(1)
	for _, field := range x.ws.Fields {
		field.Number = tagid
		tagid++
	}
	for _, field := range x.ws.Fields {
		if err := x.exportField(depth, field, x.ws.Name, nil); err != nil {
			return err
		}
	}
	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

func (x *sheetExporter) exportUnion() error {
	x.p.P("message ", x.ws.Name, " {")
	opts := &tableaupb.UnionOptions{Name: x.ws.GetOptions().GetName(), Note: x.ws.Note}
	x.p.P("  option (tableau.union) = {", marshalToText(opts), "};")
	x.p.P()

	typeOpts := &tableaupb.FieldOptions{Name: "Type"}
	x.p.P("  Type type = 9999 [(tableau.field) = {", marshalToText(typeOpts), "}];")
	x.p.P(`  oneof value {`)

	oneOfOpts := &tableaupb.OneofOptions{Note: x.ws.Note, Field: "Field"}
	x.p.P("    option (tableau.oneof) = {", marshalToText(oneOfOpts), "};")
	x.p.P()

	for _, field := range x.ws.Fields {
		ename := "TYPE_" + strcase.FromContext(x.be.gen.ctx).ToScreamingSnake(field.Name)
		typ := field.Name
		if field.FullType != "" {
			typ = field.FullType
		}
		if len(field.Fields) == 0 && field.Type == "" {
			x.p.P("    // No field bound to enum value: ", ename, ".")
		} else {
			x.p.P("    ", typ, " ", strcase.FromContext(x.be.gen.ctx).ToSnake(field.Name), " = ", field.Number, `; // Bound to enum value: `, ename, ".")
		}
	}
	x.p.P(`  }`)
	x.p.P()

	// generate enum type
	x.p.P("  enum Type {")
	x.p.P("    TYPE_INVALID = 0;")
	for _, field := range x.ws.Fields {
		ename := "TYPE_" + strcase.FromContext(x.be.gen.ctx).ToScreamingSnake(field.Name)
		note := ""
		if field.Alias != "" {
			note = " // " + field.Alias
		}
		x.p.P("    ", ename, " = ", field.Number, ` [(tableau.evalue).name = "`, field.Alias, `"];`, note)
	}
	x.p.P("  }")
	x.p.P()

	// generate message type
	for _, msgField := range x.ws.Fields {
		if len(msgField.Fields) == 0 {
			continue
		}
		typ := msgField.Name
		if msgField.Type != "" {
			typ = msgField.Type
		}
		x.p.P("  message ", typ, " {")
		// generate the fields
		depth := 2
		tagid := int32(1)
		for _, field := range msgField.Fields {
			field.Number = tagid
			cross := field.GetOptions().GetProp().GetCross()
			if cross < 1 {
				cross = 1
			}
			tagid += cross
		}
		for _, field := range msgField.Fields {
			if err := x.exportField(depth, field, msgField.Name, nil); err != nil {
				return err
			}
		}
		x.p.P("  }")
	}

	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

func (x *sheetExporter) parseMessagerFromGeneratedProtos(name string) protoreflect.MessageDescriptor {
	relPath := x.be.GetProtoFilePath()
	fd, err := x.be.gen.GeneratedProtoRegistryFiles.FindFileByPath(relPath)
	if err != nil {
		return nil
	}
	return fd.Messages().ByName(protoreflect.Name(name))
}

func (_ *sheetExporter) addNumberToFields(fields []*internalpb.Field, md protoreflect.MessageDescriptor) {
	if md == nil {
		tagid := int32(1)
		for _, field := range fields {
			field.Number = tagid
			tagid++
		}
		return
	}
	fieldNameNumberMap := make(map[string]int32)
	fieldNumbers := make(map[int32]bool)
	for _, field := range fields {
		if fd := md.Fields().ByName(protoreflect.Name(field.Name)); fd != nil {
			number := int32(fd.Number())
			fieldNameNumberMap[field.Name] = number
			fieldNumbers[number] = true
		}
	}
	var missingNumbers []int32
	for i := int32(1); len(fieldNumbers)+len(missingNumbers) < len(fields); i++ {
		if fieldNumbers[i] {
			continue
		}
		missingNumbers = append(missingNumbers, i)
	}
	missingNumberIndex := 0
	for _, field := range fields {
		if number, ok := fieldNameNumberMap[field.Name]; ok {
			field.Number = number
		} else {
			field.Number = missingNumbers[missingNumberIndex]
			missingNumberIndex++
		}
	}
}

func (x *sheetExporter) exportMessager() error {
	// log.Debugf("workbook: %s", x.ws.String())
	if x.be.messagerPatternRegexp != nil && !x.be.messagerPatternRegexp.MatchString(x.ws.Name) {
		return xerrors.Newf("messager %s does not match pattern %q", x.ws.Name, x.be.messagerPatternRegexp.String())
	}
	x.p.P("message ", x.ws.Name, " {")
	x.p.P("  option (tableau.worksheet) = {", marshalToText(x.ws.Options), "};")
	x.p.P("")

	md := x.parseMessagerFromGeneratedProtos(x.ws.Name)
	x.addNumberToFields(x.ws.Fields, md)
	// generate the fields
	depth := 1
	for _, field := range x.ws.Fields {
		var fd protoreflect.FieldDescriptor
		if md != nil {
			fd = md.Fields().ByNumber(protoreflect.FieldNumber(field.GetNumber()))
		}
		if err := x.exportField(depth, field, x.ws.Name, fd); err != nil {
			return err
		}
	}
	x.p.P("}")
	if !x.isLastSheet {
		x.p.P("")
	}
	return nil
}

func (x *sheetExporter) exportField(depth int, field *internalpb.Field, prefix string, fd protoreflect.FieldDescriptor) error {
	label := ""
	if x.ws.GetOptions().GetFieldPresence() &&
		types.IsScalarType(field.FullType) &&
		!types.IsWellKnownMessage(field.FullType) {
		label = "optional "
	}
	note := ""
	if field.Note != "" {
		note = " // " + field.Note
	}
	x.p.P(printer.Indent(depth), label, field.FullType, " ", field.Name, " = ", field.Number, " ", genFieldOptionsString(field.Options), ";", note)

	var md protoreflect.MessageDescriptor
	if fd != nil {
		md = fd.Message()
	}
	typeName := field.Type
	fullTypeName := field.FullType
	if field.ListEntry != nil {
		typeName = field.ListEntry.ElemType
		fullTypeName = field.ListEntry.ElemFullType
	}
	if field.MapEntry != nil {
		typeName = field.MapEntry.ValueType
		fullTypeName = field.MapEntry.ValueFullType
		if fd != nil {
			if v := fd.MapValue(); v != nil {
				md = v.Message()
			}
		}
	}

	if types.IsWellKnownMessage(fullTypeName) {
		importPath := types.GetWellKnownMessageImport(fullTypeName)
		x.Imports[importPath] = true
	}

	if field.Predefined {
		// import the predefined type's parent filename.
		// NOTE: excludes self.
		if typeInfo := x.typeInfos.GetByFullName(protoreflect.FullName(fullTypeName)); typeInfo != nil &&
			typeInfo.ParentFilename != x.be.GetProtoFilePath() {
			x.Imports[typeInfo.ParentFilename] = true
		}
	} else {
		nestedMsgName := prefix + "." + typeName
		switch {
		case field.Fields != nil:
			// iff field is a map or list and message type is not imported.
			if isSameFieldMessageType(field, x.nestedMessages[nestedMsgName]) {
				// if the nested message is the same as the previous one,
				// just use the previous one, and don't generate a new one.
				return nil
			}
		case !types.IsScalarType(typeName):
			if _, ok := x.nestedMessages[nestedMsgName]; ok {
				// if the nested message has the same name with the previous one,
				// just use the previous one, and don't generate a new one.
				return nil
			}
		default:
			return nil
		}
		// bookkeeping this nested msessage, so we can check if we can reuse it later.
		x.nestedMessages[nestedMsgName] = field

		// x.g.P("")
		x.p.P(printer.Indent(depth), "message ", typeName, " {")

		x.addNumberToFields(field.Fields, md)
		for _, f := range field.Fields {
			var nextFd protoreflect.FieldDescriptor
			if md != nil {
				nextFd = md.Fields().ByNumber(protoreflect.FieldNumber(field.GetNumber()))
			}
			if err := x.exportField(depth+1, f, nestedMsgName, nextFd); err != nil {
				return err
			}
		}
		x.p.P(printer.Indent(depth), "}")
	}
	return nil
}

func genFieldOptionsString(opts *tableaupb.FieldOptions) string {
	jsonName := ""
	// remember and then clear protobuf built-in options
	if opts.Prop != nil {
		jsonName = opts.Prop.JsonName
		opts.Prop.JsonName = ""

		// set nil if field prop is empty
		if IsEmptyFieldProp(opts.Prop) {
			opts.Prop = nil
		}
	}

	// compose this field options
	fieldOpts := "[(tableau.field) = {" + marshalToText(opts) + "}"
	if jsonName != "" {
		fieldOpts += `, json_name="` + jsonName + `"`
	}
	fieldOpts += "]"
	return fieldOpts
}

func marshalToText(m protoreflect.ProtoMessage) string {
	// text := proto.CompactTextString(field.Options)
	bin, err := prototext.Marshal(m)
	if err != nil {
		panic(err)
	}
	// NOTE: remove redundant spaces/whitespace from a string
	// refer: https://stackoverflow.com/questions/37290693/how-to-remove-redundant-spaces-whitespace-from-a-string-in-golang
	text := strings.Join(strings.Fields(string(bin)), " ")
	return text
}

func isSameFieldMessageType(left, right *internalpb.Field) bool {
	if left.GetType() == right.GetType() &&
		left.GetFullType() == right.GetFullType() &&
		len(left.GetFields()) == len(right.GetFields()) {
		for i, l := range left.GetFields() {
			r := right.GetFields()[i]
			if !isSameFieldMessageType(l, r) {
				return false
			}
		}
		return true
	}
	return false
}
