package protogen

import (
	"maps"
	"os"
	"slices"
	"sync"

	"github.com/tableauio/tableau/internal/x/xerrors"
	"github.com/tableauio/tableau/internal/x/xfs"
	"github.com/tableauio/tableau/log"
)

// protoOutput coordinates files generated by one run.
//
// Output workflow:
//
//	createStagingDir
//	       |
//	       v
//	reservePath -> stageFile  (concurrent for each workbook)
//	       |
//	       v
//	publishAll / publishSelected
//	       |
//	       v
//	removeStagingDir
//
// Publication starts after every worker has reserved and staged its output.
//
// This keeps parsing and rendering failures from changing existing output. Path
// reservations detect filename conflicts before publication, and publication
// preserves imported and handwritten protos while removing stale generated files
// only after replacements succeed.
type protoOutput struct {
	outputDir  string
	stagingDir string

	mu             sync.Mutex
	reservations   map[string]string // output path -> workbook path
	stagedFiles    map[string]string // output path -> temporary file
	protectedPaths map[string]bool   // configured ProtoFiles
}

// newProtoOutput creates the per-run coordinator for generated proto files.
func newProtoOutput(outputDir string, protectedPaths map[string]bool) *protoOutput {
	return &protoOutput{
		outputDir:      outputDir,
		reservations:   make(map[string]string),
		stagedFiles:    make(map[string]string),
		protectedPaths: protectedPaths,
	}
}

// createStagingDir creates a private directory for files produced by this run.
//
// It is created under outputDir so staged files and their destinations are on
// the same volume. This lets publication replace files with os.Rename, which
// is atomic and does not support cross-volume moves on Windows.
func (out *protoOutput) createStagingDir() error {
	stagingDir, err := os.MkdirTemp(out.outputDir, ".tableau-staging-")
	if err != nil {
		return xerrors.WrapKV(err, xerrors.KeyOutdir, out.outputDir)
	}
	out.stagingDir = stagingDir
	return nil
}

// removeStagingDir removes staged files after publication or a failed run.
func (out *protoOutput) removeStagingDir() {
	if out.stagingDir == "" {
		return
	}
	if err := os.RemoveAll(out.stagingDir); err != nil {
		log.Warnf("failed to remove staging proto files in %s: %v", out.stagingDir, err)
	}
	out.stagingDir = ""
}

// reservePath assigns an output path to one workbook before that workbook writes it.
func (out *protoOutput) reservePath(outputPath, workbookPath string) error {
	key, err := xfs.Abs(outputPath)
	if err != nil {
		return err
	}
	out.mu.Lock()
	defer out.mu.Unlock()
	if owner, ok := out.reservations[key]; ok {
		return xerrors.E1000(key, owner, workbookPath)
	}
	if out.protectedPaths[key] {
		return xerrors.Newf("proto output conflicts with imported proto file: %s", key)
	}
	if err := validateExistingGeneratedProto(outputPath); err != nil {
		return err
	}
	out.reservations[key] = workbookPath
	return nil
}

// stageFile writes a complete reserved output to a uniquely named staging file.
//
// Workers may stage files concurrently. A temporary name avoids collisions, and
// the file is recorded for publication only after it closes successfully. The
// generated filename is used only when publish replaces its final destination.
func (out *protoOutput) stageFile(outputPath string, parts ...[]byte) error {
	key, err := xfs.Abs(outputPath)
	if err != nil {
		return err
	}
	out.mu.Lock()
	_, reserved := out.reservations[key]
	out.mu.Unlock()
	if !reserved {
		return xerrors.Newf("proto output path was not reserved: %s", outputPath)
	}
	f, err := os.CreateTemp(out.stagingDir, "proto-*.tmp")
	if err != nil {
		return xerrors.WrapKV(err)
	}
	for _, part := range parts {
		if _, err := f.Write(part); err != nil {
			_ = f.Close()
			_ = os.Remove(f.Name())
			return xerrors.WrapKV(err)
		}
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(f.Name())
		return xerrors.WrapKV(err)
	}
	out.mu.Lock()
	out.stagedFiles[key] = f.Name()
	out.mu.Unlock()
	return nil
}

// publishAll replaces generated files and then removes stale generated files.
func (out *protoOutput) publishAll() error {
	stalePaths, err := findStaleProtoFiles(out.outputDir, out.reservations, out.protectedPaths)
	if err != nil {
		return err
	}
	return out.publish(stalePaths)
}

// publishSelected replaces generated files without removing other outputs.
func (out *protoOutput) publishSelected() error {
	return out.publish(nil)
}

// publish replaces staged files, then removes the supplied stale files.
func (out *protoOutput) publish(stalePaths []string) error {
	paths := slices.Sorted(maps.Keys(out.stagedFiles))
	for _, path := range paths {
		if err := validateExistingGeneratedProto(path); err != nil {
			return err
		}
		if err := os.Rename(out.stagedFiles[path], path); err != nil {
			return xerrors.WrapKV(err)
		}
	}
	for _, path := range stalePaths {
		if err := validateExistingGeneratedProto(path); err != nil {
			return err
		}
		if err := os.Remove(path); err != nil {
			return xerrors.WrapKV(err)
		}
		log.Infof("%15s: %s", "removed stale proto", path)
	}
	return nil
}
