package protogen

import (
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sync"

	"github.com/tableauio/tableau/internal/importer"
	"github.com/tableauio/tableau/internal/x/xerrors"
	"github.com/tableauio/tableau/internal/x/xfs"
	"github.com/tableauio/tableau/log"
)

// protoOutput owns the files generated by one run. Workers reserve and stage
// files concurrently; commit runs after all workers have finished.
type protoOutput struct {
	dir      string
	stageDir string

	mu      sync.Mutex
	owners  map[string]string // output path -> workbook path
	staged  map[string]string // output path -> temporary file
	imports map[string]bool   // configured ProtoFiles
}

func newProtoOutput(dir string, imports map[string]bool) *protoOutput {
	return &protoOutput{
		dir:     dir,
		owners:  make(map[string]string),
		staged:  make(map[string]string),
		imports: imports,
	}
}

func importedProtoPaths(patterns []string) (map[string]bool, error) {
	paths := make(map[string]bool)
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return nil, xerrors.WrapKV(err)
		}
		for _, match := range matches {
			path, err := xfs.Abs(match)
			if err != nil {
				return nil, err
			}
			paths[path] = true
		}
	}
	return paths, nil
}

func (gen *Generator) beginRun() error {
	imports, err := importedProtoPaths(gen.InputOpt.ProtoFiles)
	if err != nil {
		return err
	}
	gen.output = newProtoOutput(filepath.Join(gen.OutputDir, gen.OutputOpt.Subdir), imports)
	gen.collector = xerrors.NewCollector(gen.ErrorLimitOpt.MaxErrors)
	gen.registryWithGeneratedOnce = sync.Once{}
	gen.protoRegistryFilesWithGenerated = nil
	gen.cacheMu.Lock()
	gen.cachedImporters = make(map[string]importer.Importer)
	gen.cacheMu.Unlock()
	return nil
}

func (out *protoOutput) start() error {
	stageDir, err := os.MkdirTemp(out.dir, ".tableau-stage-")
	if err != nil {
		return xerrors.WrapKV(err, xerrors.KeyOutdir, out.dir)
	}
	out.stageDir = stageDir
	return nil
}

func (out *protoOutput) discard() {
	if out.stageDir == "" {
		return
	}
	if err := os.RemoveAll(out.stageDir); err != nil {
		log.Warnf("failed to remove temporary proto files in %s: %v", out.stageDir, err)
	}
	out.stageDir = ""
}

// existingGeneratedProto returns whether path exists and may be replaced.
func existingGeneratedProto(path string) (bool, error) {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, xerrors.WrapKV(err)
	}
	if !info.Mode().IsRegular() {
		return false, xerrors.Newf("proto output is not a regular file: %s", path)
	}
	generated, err := isGeneratedProtoFile(path)
	if err != nil {
		return false, err
	}
	if !generated {
		return false, xerrors.Newf("refusing to overwrite non-generated proto file: %s", path)
	}
	return true, nil
}

func (out *protoOutput) register(path, bookPath string) error {
	key, err := xfs.Abs(path)
	if err != nil {
		return err
	}
	out.mu.Lock()
	defer out.mu.Unlock()
	if owner, ok := out.owners[key]; ok {
		return xerrors.E1000(key, owner, bookPath)
	}
	if out.imports[key] {
		return xerrors.Newf("proto output conflicts with imported proto file: %s", key)
	}
	if _, err := existingGeneratedProto(path); err != nil {
		return err
	}
	out.owners[key] = bookPath
	return nil
}

func (out *protoOutput) stage(path string, parts ...[]byte) error {
	key, err := xfs.Abs(path)
	if err != nil {
		return err
	}
	f, err := os.CreateTemp(out.stageDir, "proto-*.tmp")
	if err != nil {
		return xerrors.WrapKV(err)
	}
	for _, part := range parts {
		if _, err := f.Write(part); err != nil {
			_ = f.Close()
			_ = os.Remove(f.Name())
			return xerrors.WrapKV(err)
		}
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(f.Name())
		return xerrors.WrapKV(err)
	}
	out.mu.Lock()
	out.staged[key] = f.Name()
	out.mu.Unlock()
	return nil
}

// publish replaces generated files after rendering succeeds. It removes stale
// files only after all replacements succeed.
func (out *protoOutput) publish(removeStale bool) error {
	var stale []string
	if removeStale {
		var err error
		stale, err = staleProtoFiles(out.dir, out.owners, out.imports)
		if err != nil {
			return err
		}
	}

	paths := slices.Sorted(maps.Keys(out.staged))
	for _, path := range paths {
		if _, err := existingGeneratedProto(path); err != nil {
			return err
		}
		if err := os.Rename(out.staged[path], path); err != nil {
			return xerrors.WrapKV(err)
		}
	}
	for _, path := range stale {
		if _, err := existingGeneratedProto(path); err != nil {
			return err
		}
		if err := os.Remove(path); err != nil {
			return xerrors.WrapKV(err)
		}
		log.Infof("%15s: %s", "removed stale proto", path)
	}
	return nil
}
