package protogen

import (
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/tableauio/tableau/internal/x/xerrors"
	"github.com/tableauio/tableau/internal/x/xfs"
	"github.com/tableauio/tableau/log"
)

type parsePass int

const (
	firstPass  parsePass = iota // only generate type definitions from sheets
	secondPass                  // generate config messagers from sheets
)

// generatedFileHeaderPrefix is the prefix of the first line of each proto file
// generated by protogen, which is written by the exporter and marks the file as
// owned by tableau, so that the stale ones can be swept without touching the
// handwritten ones.
//
// NOTE: the version part is intentionally excluded, so as to also recognize the
// proto files generated by other versions of tableau.
const generatedFileHeaderPrefix = "// Code generated by tableau"

func prepareOutdir(outdir string) error {
	if err := os.MkdirAll(outdir, xfs.DefaultDirPerm); err != nil {
		return xerrors.WrapKV(err, xerrors.KeyOutdir, outdir)
	}
	return nil
}

// isGeneratedProtoFile reports whether a proto starts with tableau's header.
func isGeneratedProtoFile(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, xerrors.WrapKV(err)
	}
	defer f.Close()

	header := make([]byte, len(generatedFileHeaderPrefix))
	if _, err := io.ReadFull(f, header); err != nil {
		if err == io.EOF || err == io.ErrUnexpectedEOF {
			return false, nil
		}
		return false, xerrors.WrapKV(err)
	}
	return string(header) == generatedFileHeaderPrefix, nil
}

func absoluteProtoPath(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", xerrors.WrapKV(err)
	}
	return xfs.CleanSlashPath(abs), nil
}

// staleProtoFiles only inspects this generator's output directory. Nested
// directories may belong to a separate generator.
func staleProtoFiles(outdir string, generatedPaths, protectedPaths map[string]bool) ([]string, error) {
	entries, err := os.ReadDir(outdir)
	if err != nil {
		return nil, xerrors.WrapKV(err, xerrors.KeyOutdir, outdir)
	}
	var stale []string
	for _, entry := range entries {
		if !entry.Type().IsRegular() || !strings.HasSuffix(entry.Name(), ".proto") {
			continue
		}
		path := filepath.Join(outdir, entry.Name())
		key, err := absoluteProtoPath(path)
		if err != nil {
			return nil, err
		}
		if generatedPaths[key] || protectedPaths[key] {
			continue
		}
		generated, err := isGeneratedProtoFile(path)
		if err != nil {
			return nil, err
		}
		if generated {
			stale = append(stale, path)
		}
	}
	return stale, nil
}

// sweepOutdir removes stale generated protos owned by this output directory.
func sweepOutdir(outdir string, generatedPaths, protectedPaths map[string]bool) error {
	stale, err := staleProtoFiles(outdir, generatedPaths, protectedPaths)
	if err != nil {
		return err
	}
	for _, path := range stale {
		if err := os.Remove(path); err != nil {
			return xerrors.WrapKV(err)
		}
		log.Infof("%15s: %s", "removed stale proto", path)
	}
	return nil
}

func getRelCleanSlashPath(rootdir, dir, filename string) (string, error) {
	relativeDir, err := filepath.Rel(rootdir, dir)
	if err != nil {
		return "", xerrors.Newf("failed to get relative path from %s to %s: %s", rootdir, dir, err)
	}
	// relative slash separated path
	relativePath := filepath.Join(relativeDir, filename)
	relSlashPath := filepath.ToSlash(filepath.Clean(relativePath))
	return relSlashPath, nil
}

func genProtoFilePath(bookName, suffix string) string {
	return bookName + suffix + ".proto"
}

func wrapDebugErr(err error, bookName, sheetName string, header *tableHeader, cursor int) error {
	getCellPos := func(row int) string {
		return header.Position(row-1, cursor)
	}
	return xerrors.WrapKV(err,
		xerrors.KeyBookName, bookName,
		xerrors.KeySheetName, sheetName,
		xerrors.KeyNameCellPos, getCellPos(header.NameRow),
		xerrors.KeyTypeCellPos, getCellPos(header.TypeRow),
		xerrors.KeyNoteCellPos, getCellPos(header.NoteRow),
		xerrors.KeyNameCell, header.getNameCell(cursor),
		xerrors.KeyTypeCell, header.getTypeCell(cursor),
		xerrors.KeyNoteCell, header.getNoteCell(cursor),
	)
}
