package protogen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/tableauio/tableau/internal/importer/book"
	"github.com/tableauio/tableau/internal/importer/book/tableparser"
	"github.com/tableauio/tableau/internal/x/xerrors"
	"github.com/tableauio/tableau/internal/x/xfs"
)

func Test_prepareOutdir(t *testing.T) {
	t.Run("new-outdir", func(t *testing.T) {
		outdir := filepath.Join(t.TempDir(), "path/to/dir")
		require.NoError(t, prepareOutdir(outdir))
		require.DirExists(t, outdir)
	})

	t.Run("existed-outdir", func(t *testing.T) {
		outdir := t.TempDir()
		existed := filepath.Join(outdir, "common.proto")
		require.NoError(t, os.WriteFile(existed, []byte("// handwritten\n"), 0o644))
		require.NoError(t, prepareOutdir(outdir))
		// NOTE: prepareOutdir must never remove anything, so that a failed run
		// leaves the previously generated proto files intact.
		require.FileExists(t, existed)
	})
}

// generatedFileHeaderLine returns the same first line as the exporter writes
// for each generated proto file.
func generatedFileHeaderLine() string {
	return generatedFileHeaderPrefix + " (protogen v" + Version + "). DO NOT EDIT.\n"
}

func Test_isGeneratedProtoFile(t *testing.T) {
	dir := t.TempDir()
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "generated by the current version",
			content: generatedFileHeaderLine(),
			want:    true,
		},
		{
			// NOTE: the header is intentionally hardcoded here, as it is
			// persisted in the proto files generated by older versions of
			// tableau, which must keep being recognized.
			name:    "generated by another version",
			content: "// Code generated by tableau (protogen v0.1.0). DO NOT EDIT.\n",
			want:    true,
		},
		{
			name:    "handwritten",
			content: "syntax = \"proto3\";\n",
			want:    false,
		},
		{
			name:    "generated by another tool",
			content: "// Code generated by protoc-gen-go. DO NOT EDIT.\n",
			want:    false,
		},
		{
			name:    "empty file",
			content: "",
			want:    false,
		},
		{
			name:    "shorter than the header",
			content: "// Code\n",
			want:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(dir, "test.proto")
			require.NoError(t, os.WriteFile(path, []byte(tt.content), 0o644))
			got, err := isGeneratedProtoFile(path)
			require.NoError(t, err)
			require.Equal(t, tt.want, got)
		})
	}
}

func Test_sweepOutdir(t *testing.T) {
	generatedHeader := generatedFileHeaderLine()

	// setupOutdir creates an outdir with the given files, whose content is
	// keyed by the relative path.
	setupOutdir := func(t *testing.T, files map[string]string) string {
		t.Helper()
		outdir := t.TempDir()
		for name, content := range files {
			path := filepath.Join(outdir, name)
			require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
			require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
		}
		return outdir
	}

	t.Run("remove stale but keep generated and handwritten", func(t *testing.T) {
		outdir := setupOutdir(t, map[string]string{
			"item_conf.proto":   generatedHeader,
			"stale_conf.proto":  generatedHeader,
			"handwritten.proto": "syntax = \"proto3\";\n",
			"not_a_proto.txt":   generatedHeader,
		})
		generatedPaths := map[string]bool{
			xfs.CleanSlashPath(filepath.Join(outdir, "item_conf.proto")): true,
		}
		require.NoError(t, sweepOutdir(outdir, generatedPaths))

		require.FileExists(t, filepath.Join(outdir, "item_conf.proto"))
		// the handwritten one has no generated header, so it must be kept even
		// though it is not generated in this run
		require.FileExists(t, filepath.Join(outdir, "handwritten.proto"))
		// non-proto files are never touched
		require.FileExists(t, filepath.Join(outdir, "not_a_proto.txt"))
		require.NoFileExists(t, filepath.Join(outdir, "stale_conf.proto"))
	})

	t.Run("sweep recursively", func(t *testing.T) {
		outdir := setupOutdir(t, map[string]string{
			"sub/stale_conf.proto":  generatedHeader,
			"sub/handwritten.proto": "syntax = \"proto3\";\n",
		})
		require.NoError(t, sweepOutdir(outdir, nil))
		require.NoFileExists(t, filepath.Join(outdir, "sub/stale_conf.proto"))
		require.FileExists(t, filepath.Join(outdir, "sub/handwritten.proto"))
	})

	t.Run("nothing to sweep", func(t *testing.T) {
		outdir := setupOutdir(t, map[string]string{"item_conf.proto": generatedHeader})
		generatedPaths := map[string]bool{
			xfs.CleanSlashPath(filepath.Join(outdir, "item_conf.proto")): true,
		}
		require.NoError(t, sweepOutdir(outdir, generatedPaths))
		require.FileExists(t, filepath.Join(outdir, "item_conf.proto"))
	})
}

func Test_getRelCleanSlashPath(t *testing.T) {
	type args struct {
		rootdir  string
		dir      string
		filename string
	}
	tests := []struct {
		name    string
		args    args
		want    string
		wantErr bool
	}{
		{
			name: "relative-clean-slash-path",
			args: args{
				rootdir:  "testdata",
				dir:      `./testdata/output/proto/`,
				filename: "common.proto",
			},
			want:    "output/proto/common.proto",
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := getRelCleanSlashPath(tt.args.rootdir, tt.args.dir, tt.args.filename)
			if (err != nil) != tt.wantErr {
				t.Errorf("getRelCleanSlashPath() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("getRelCleanSlashPath() = %v, want %v", got, tt.want)
			}
		})
	}
}

func Test_genProtoFilePath(t *testing.T) {
	type args struct {
		bookName string
		suffix   string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "merge-header-options",
			args: args{
				bookName: "item",
				suffix:   "_conf",
			},
			want: "item_conf.proto",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := genProtoFilePath(tt.args.bookName, tt.args.suffix); got != tt.want {
				t.Errorf("genProtoFilePath() = %v, want %v", got, tt.want)
			}
		})
	}
}

func Test_wrapDebugErr(t *testing.T) {
	testTransposeSheetHeader := &tableHeader{
		Header: &tableparser.Header{
			NameRow: 1,
			TypeRow: 2,
			NoteRow: 3,
		},
		Positioner:  &book.TransposedTable{},
		nameRowData: []string{"ID", "Value", "", "Kind"},
		typeRowData: []string{"map<int32, Item>", "int32", "", "int32"},
		noteRowData: []string{"Item's ID", "Item's value", "", "Item's kind"},
		validNames:  map[string]int{},
	}

	type args struct {
		err       error
		bookName  string
		sheetName string
		sh        *tableHeader
		cursor    int
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
		err     error
	}{
		{
			name: "E0001",
			args: args{
				err:       xerrors.E0001("TestSheet", "TestBook"),
				bookName:  "TestBook",
				sheetName: "TestSheet",
				sh:        testSheetHeader,
				cursor:    0,
			},
			err:     xerrors.ErrE0001,
			wantErr: true,
		},
		{
			name: "E0001 transpose",
			args: args{
				err:       xerrors.E0001("TestSheet", "TestBook"),
				bookName:  "TestBook",
				sheetName: "TestSheet",
				sh:        testTransposeSheetHeader,
				cursor:    0,
			},
			err:     xerrors.ErrE0001,
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := wrapDebugErr(tt.args.err, tt.args.bookName, tt.args.sheetName, tt.args.sh, tt.args.cursor)
			if (err != nil) != tt.wantErr {
				t.Errorf("wrapDebugErr() error = %v, wantErr %v", err, tt.wantErr)
			}
			if err != nil {
				require.ErrorIs(t, err, tt.err)
				desc := xerrors.NewDesc(err)
				require.Equal(t, desc.GetValue(xerrors.KeyBookName), tt.args.bookName)
				require.Equal(t, desc.GetValue(xerrors.KeySheetName), tt.args.sheetName)
			}
		})
	}
}
