package protogen

import (
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/tableauio/tableau/internal/x/xerrors"
	"github.com/tableauio/tableau/internal/x/xfs"
	"github.com/tableauio/tableau/log"
)

type parsePass int

const (
	firstPass  parsePass = iota // only generate type definitions from sheets
	secondPass                  // generate config messagers from sheets
)

// generatedFileHeaderPrefix is the prefix of the first line of each proto file
// generated by protogen, which is written by the exporter and marks the file as
// owned by tableau, so that the stale ones can be swept without touching the
// handwritten ones.
//
// NOTE: the version part is intentionally excluded, so as to also recognize the
// proto files generated by other versions of tableau.
const generatedFileHeaderPrefix = "// Code generated by tableau"

func prepareOutdir(outdir string) error {
	if err := os.MkdirAll(outdir, xfs.DefaultDirPerm); err != nil {
		return xerrors.WrapKV(err, xerrors.KeyOutdir, outdir)
	}
	return nil
}

// isGeneratedProtoFile reports whether the proto file at the given path was
// generated by protogen, aka having the generated file header.
func isGeneratedProtoFile(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, xerrors.WrapKV(err)
	}
	defer f.Close()
	// the header is always the first line, so there is no need to scan the
	// whole file.
	header := make([]byte, len(generatedFileHeaderPrefix))
	if _, err := io.ReadFull(f, header); err != nil {
		if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
			return false, nil
		}
		return false, xerrors.WrapKV(err)
	}
	return string(header) == generatedFileHeaderPrefix, nil
}

// sweepOutdir removes the stale proto files in outdir recursively, aka those
// generated by protogen previously but not generated in this run any more,
// mostly because the corresponding workbooks were renamed or deleted.
//
// NOTE:
//   - It must be called after all proto files are generated successfully,
//     otherwise the ones to be generated later would be mistaken for stale, and
//     a failed run would leave the outdir incomplete.
//   - The handwritten proto files are never removed, as they do not have the
//     generated file header.
func sweepOutdir(outdir string, generatedPaths map[string]bool) error {
	return filepath.WalkDir(outdir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return xerrors.WrapKV(err, xerrors.KeyOutdir, outdir)
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".proto") {
			return nil
		}
		if generatedPaths[xfs.CleanSlashPath(path)] {
			return nil
		}
		generated, err := isGeneratedProtoFile(path)
		if err != nil {
			return err
		}
		if !generated {
			log.Debugf("keep handwritten proto file: %s", path)
			return nil
		}
		if err := os.Remove(path); err != nil {
			return xerrors.WrapKV(err)
		}
		log.Infof("%15s: %s", "removed stale proto", path)
		return nil
	})
}

func getRelCleanSlashPath(rootdir, dir, filename string) (string, error) {
	relativeDir, err := filepath.Rel(rootdir, dir)
	if err != nil {
		return "", xerrors.Newf("failed to get relative path from %s to %s: %s", rootdir, dir, err)
	}
	// relative slash separated path
	relativePath := filepath.Join(relativeDir, filename)
	relSlashPath := filepath.ToSlash(filepath.Clean(relativePath))
	return relSlashPath, nil
}

func genProtoFilePath(bookName, suffix string) string {
	return bookName + suffix + ".proto"
}

func wrapDebugErr(err error, bookName, sheetName string, header *tableHeader, cursor int) error {
	getCellPos := func(row int) string {
		return header.Position(row-1, cursor)
	}
	return xerrors.WrapKV(err,
		xerrors.KeyBookName, bookName,
		xerrors.KeySheetName, sheetName,
		xerrors.KeyNameCellPos, getCellPos(header.NameRow),
		xerrors.KeyTypeCellPos, getCellPos(header.TypeRow),
		xerrors.KeyNoteCellPos, getCellPos(header.NoteRow),
		xerrors.KeyNameCell, header.getNameCell(cursor),
		xerrors.KeyTypeCell, header.getTypeCell(cursor),
		xerrors.KeyNoteCell, header.getNoteCell(cursor),
	)
}
