// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.5
// source: tableau/protobuf/tableau.proto

package tableaupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Layout of list and map.
type Layout int32

const (
	// Default:
	//  - vertical for struct map
	//  - incell for scalar map
	//  - horizontal for struct list
	//  - incell for scalar list
	Layout_LAYOUT_DEFAULT    Layout = 0
	Layout_LAYOUT_VERTICAL   Layout = 1 // Vertical
	Layout_LAYOUT_HORIZONTAL Layout = 2 // Horizontal
	Layout_LAYOUT_INCELL     Layout = 3 // Incell
)

// Enum value maps for Layout.
var (
	Layout_name = map[int32]string{
		0: "LAYOUT_DEFAULT",
		1: "LAYOUT_VERTICAL",
		2: "LAYOUT_HORIZONTAL",
		3: "LAYOUT_INCELL",
	}
	Layout_value = map[string]int32{
		"LAYOUT_DEFAULT":    0,
		"LAYOUT_VERTICAL":   1,
		"LAYOUT_HORIZONTAL": 2,
		"LAYOUT_INCELL":     3,
	}
)

func (x Layout) Enum() *Layout {
	p := new(Layout)
	*p = x
	return p
}

func (x Layout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layout) Descriptor() protoreflect.EnumDescriptor {
	return file_tableau_protobuf_tableau_proto_enumTypes[0].Descriptor()
}

func (Layout) Type() protoreflect.EnumType {
	return &file_tableau_protobuf_tableau_proto_enumTypes[0]
}

func (x Layout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layout.Descriptor instead.
func (Layout) EnumDescriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{0}
}

// Field data span of scalar and struct.
type Span int32

const (
	// Default:
	//  - inner cell for scalar type: bool, string, bytes, number, and enum.
	//  - cross cell for struct type: map-value, list-element, and struct-field.
	Span_SPAN_DEFAULT    Span = 0
	Span_SPAN_CROSS_CELL Span = 1 // The field data spans cross multiple cells.
	Span_SPAN_INNER_CELL Span = 2 // The field data spans only in one cell.
)

// Enum value maps for Span.
var (
	Span_name = map[int32]string{
		0: "SPAN_DEFAULT",
		1: "SPAN_CROSS_CELL",
		2: "SPAN_INNER_CELL",
	}
	Span_value = map[string]int32{
		"SPAN_DEFAULT":    0,
		"SPAN_CROSS_CELL": 1,
		"SPAN_INNER_CELL": 2,
	}
)

func (x Span) Enum() *Span {
	p := new(Span)
	*p = x
	return p
}

func (x Span) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Span) Descriptor() protoreflect.EnumDescriptor {
	return file_tableau_protobuf_tableau_proto_enumTypes[1].Descriptor()
}

func (Span) Type() protoreflect.EnumType {
	return &file_tableau_protobuf_tableau_proto_enumTypes[1]
}

func (x Span) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Span.Descriptor instead.
func (Span) EnumDescriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{1}
}

type WorkbookOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // workbook name
}

func (x *WorkbookOptions) Reset() {
	*x = WorkbookOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableau_protobuf_tableau_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkbookOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkbookOptions) ProtoMessage() {}

func (x *WorkbookOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tableau_protobuf_tableau_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkbookOptions.ProtoReflect.Descriptor instead.
func (*WorkbookOptions) Descriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{0}
}

func (x *WorkbookOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorksheetOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`            // worksheet name
	Namerow   int32  `protobuf:"varint,2,opt,name=namerow,proto3" json:"namerow,omitempty"`     // [default = 1]; // exact row number of name at worksheet.
	Typerow   int32  `protobuf:"varint,3,opt,name=typerow,proto3" json:"typerow,omitempty"`     // [default = 2]; // exact row number of type at worksheet, for generating protos.
	Noterow   int32  `protobuf:"varint,4,opt,name=noterow,proto3" json:"noterow,omitempty"`     // [default = 3]; // exact row number of note at worksheet.
	Datarow   int32  `protobuf:"varint,5,opt,name=datarow,proto3" json:"datarow,omitempty"`     // [default = 4]; // start row number of data at worksheet.
	Transpose bool   `protobuf:"varint,6,opt,name=transpose,proto3" json:"transpose,omitempty"` // [default = false]; // interchange the rows and columns
	Tags      string `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`            // [default = ""]; // tags for usage, e.g.: "1,2" specifying loading servers. Speciallly, "*"
	// means all servers.
	Nameline      int32    `protobuf:"varint,8,opt,name=nameline,proto3" json:"nameline,omitempty"`                                 // [default = 0]; // specify which line in cell as name, '0' means the whole cell is name.
	Typeline      int32    `protobuf:"varint,9,opt,name=typeline,proto3" json:"typeline,omitempty"`                                 // [default = 0]; // specify which line in cell as type,'0' means the whole cell is type.
	Nested        bool     `protobuf:"varint,10,opt,name=nested,proto3" json:"nested,omitempty"`                                    // [default = false]; // whether the naming of name row is nested.
	Sep           string   `protobuf:"bytes,11,opt,name=sep,proto3" json:"sep,omitempty"`                                           // separator, default: ","
	Subsep        string   `protobuf:"bytes,12,opt,name=subsep,proto3" json:"subsep,omitempty"`                                     // subseparator, default: ":"
	Merger        []string `protobuf:"bytes,13,rep,name=merger,proto3" json:"merger,omitempty"`                                     // [default = ""]; // merge multiple sheets by the merger pattern.
	AdjacentKey   bool     `protobuf:"varint,14,opt,name=adjacent_key,json=adjacentKey,proto3" json:"adjacent_key,omitempty"`       // [default = false]; // whether the rows with the same key is adjacent together.
	FieldPresence bool     `protobuf:"varint,15,opt,name=field_presence,json=fieldPresence,proto3" json:"field_presence,omitempty"` // [default = false]; // whether add the optional label to basic types.
	////////// Loader related options below //////////
	OrderedMap bool     `protobuf:"varint,50,opt,name=ordered_map,json=orderedMap,proto3" json:"ordered_map,omitempty"` // generate ordered map accessers.
	Index      []string `protobuf:"bytes,51,rep,name=index,proto3" json:"index,omitempty"`                              // generate index accessers.
}

func (x *WorksheetOptions) Reset() {
	*x = WorksheetOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableau_protobuf_tableau_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorksheetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorksheetOptions) ProtoMessage() {}

func (x *WorksheetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tableau_protobuf_tableau_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorksheetOptions.ProtoReflect.Descriptor instead.
func (*WorksheetOptions) Descriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{1}
}

func (x *WorksheetOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorksheetOptions) GetNamerow() int32 {
	if x != nil {
		return x.Namerow
	}
	return 0
}

func (x *WorksheetOptions) GetTyperow() int32 {
	if x != nil {
		return x.Typerow
	}
	return 0
}

func (x *WorksheetOptions) GetNoterow() int32 {
	if x != nil {
		return x.Noterow
	}
	return 0
}

func (x *WorksheetOptions) GetDatarow() int32 {
	if x != nil {
		return x.Datarow
	}
	return 0
}

func (x *WorksheetOptions) GetTranspose() bool {
	if x != nil {
		return x.Transpose
	}
	return false
}

func (x *WorksheetOptions) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *WorksheetOptions) GetNameline() int32 {
	if x != nil {
		return x.Nameline
	}
	return 0
}

func (x *WorksheetOptions) GetTypeline() int32 {
	if x != nil {
		return x.Typeline
	}
	return 0
}

func (x *WorksheetOptions) GetNested() bool {
	if x != nil {
		return x.Nested
	}
	return false
}

func (x *WorksheetOptions) GetSep() string {
	if x != nil {
		return x.Sep
	}
	return ""
}

func (x *WorksheetOptions) GetSubsep() string {
	if x != nil {
		return x.Subsep
	}
	return ""
}

func (x *WorksheetOptions) GetMerger() []string {
	if x != nil {
		return x.Merger
	}
	return nil
}

func (x *WorksheetOptions) GetAdjacentKey() bool {
	if x != nil {
		return x.AdjacentKey
	}
	return false
}

func (x *WorksheetOptions) GetFieldPresence() bool {
	if x != nil {
		return x.FieldPresence
	}
	return false
}

func (x *WorksheetOptions) GetOrderedMap() bool {
	if x != nil {
		return x.OrderedMap
	}
	return false
}

func (x *WorksheetOptions) GetIndex() []string {
	if x != nil {
		return x.Index
	}
	return nil
}

type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                          // scalar type's varible name or composite type's varible name (prefix).
	Note     string     `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`                          // note of name, maybe in another language (Chinese) other than variable name (English).
	Key      string     `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                            // only set when type is map or keyed-list.
	Layout   Layout     `protobuf:"varint,4,opt,name=layout,proto3,enum=tableau.Layout" json:"layout,omitempty"` // For map/list types with cardinality. Default: LAYOUT_DEFAULT.
	Span     Span       `protobuf:"varint,5,opt,name=span,proto3,enum=tableau.Span" json:"span,omitempty"`       // For list element or map value types. Default: SPAN_CROSS_CELL.
	Sep      string     `protobuf:"bytes,6,opt,name=sep,proto3" json:"sep,omitempty"`                            // separator, default: ","
	Subsep   string     `protobuf:"bytes,7,opt,name=subsep,proto3" json:"subsep,omitempty"`                      // subseparator, default: ":"
	Optional bool       `protobuf:"varint,8,opt,name=optional,proto3" json:"optional,omitempty"`                 // whether the field is optional.
	Prop     *FieldProp `protobuf:"bytes,15,opt,name=prop,proto3" json:"prop,omitempty"`                         // property of field.
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableau_protobuf_tableau_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tableau_protobuf_tableau_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldOptions) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *FieldOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldOptions) GetLayout() Layout {
	if x != nil {
		return x.Layout
	}
	return Layout_LAYOUT_DEFAULT
}

func (x *FieldOptions) GetSpan() Span {
	if x != nil {
		return x.Span
	}
	return Span_SPAN_DEFAULT
}

func (x *FieldOptions) GetSep() string {
	if x != nil {
		return x.Sep
	}
	return ""
}

func (x *FieldOptions) GetSubsep() string {
	if x != nil {
		return x.Subsep
	}
	return ""
}

func (x *FieldOptions) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *FieldOptions) GetProp() *FieldProp {
	if x != nil {
		return x.Prop
	}
	return nil
}

type FieldProp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Different interpretations of range:
	//   - number: value range
	//   - repeated: size range of array
	//   - string: count of utf-8 code point
	Range  string `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`    // Local perspective:  format: "1,10", "1,~", "~,10"
	Unique bool   `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"` // Local perspective:  whether the field's value is unique.
	Refer  string `protobuf:"bytes,3,opt,name=refer,proto3" json:"refer,omitempty"`    // Global perspective: ensure this field is in another message's field range. Example: "XXXConf.ID"
	// Local perspective: ensure this field's value is a sequence and begins with this value.
	Sequence *int64 `protobuf:"varint,4,opt,name=sequence,proto3,oneof" json:"sequence,omitempty"`
	Default  string `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"` // default value.
	Fixed    bool   `protobuf:"varint,6,opt,name=fixed,proto3" json:"fixed,omitempty"`    // fixed length of horizontal list/map.
	Length   uint32 `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`  // specified fixed length of horizontal list/map.
}

func (x *FieldProp) Reset() {
	*x = FieldProp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableau_protobuf_tableau_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldProp) ProtoMessage() {}

func (x *FieldProp) ProtoReflect() protoreflect.Message {
	mi := &file_tableau_protobuf_tableau_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldProp.ProtoReflect.Descriptor instead.
func (*FieldProp) Descriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{3}
}

func (x *FieldProp) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *FieldProp) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *FieldProp) GetRefer() string {
	if x != nil {
		return x.Refer
	}
	return ""
}

func (x *FieldProp) GetSequence() int64 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

func (x *FieldProp) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *FieldProp) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *FieldProp) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type EnumOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // alias name
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableau_protobuf_tableau_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tableau_protobuf_tableau_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{4}
}

func (x *EnumOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnumValueOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // alias name
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableau_protobuf_tableau_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tableau_protobuf_tableau_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_tableau_protobuf_tableau_proto_rawDescGZIP(), []int{5}
}

func (x *EnumValueOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_tableau_protobuf_tableau_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*WorkbookOptions)(nil),
		Field:         50000,
		Name:          "tableau.workbook",
		Tag:           "bytes,50000,opt,name=workbook",
		Filename:      "tableau/protobuf/tableau.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*WorksheetOptions)(nil),
		Field:         50000,
		Name:          "tableau.worksheet",
		Tag:           "bytes,50000,opt,name=worksheet",
		Filename:      "tableau/protobuf/tableau.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50000,
		Name:          "tableau.field",
		Tag:           "bytes,50000,opt,name=field",
		Filename:      "tableau/protobuf/tableau.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         50000,
		Name:          "tableau.enum",
		Tag:           "bytes,50000,opt,name=enum",
		Filename:      "tableau/protobuf/tableau.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         50000,
		Name:          "tableau.evalue",
		Tag:           "bytes,50000,opt,name=evalue",
		Filename:      "tableau/protobuf/tableau.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional tableau.WorkbookOptions workbook = 50000;
	E_Workbook = &file_tableau_protobuf_tableau_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional tableau.WorksheetOptions worksheet = 50000;
	E_Worksheet = &file_tableau_protobuf_tableau_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional tableau.FieldOptions field = 50000;
	E_Field = &file_tableau_protobuf_tableau_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional tableau.EnumOptions enum = 50000;
	E_Enum = &file_tableau_protobuf_tableau_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional tableau.EnumValueOptions evalue = 50000;
	E_Evalue = &file_tableau_protobuf_tableau_proto_extTypes[4]
)

var File_tableau_protobuf_tableau_proto protoreflect.FileDescriptor

var file_tableau_protobuf_tableau_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x57,
	0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xd3, 0x03, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x68, 0x65, 0x65, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x61, 0x6d, 0x65, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x61,
	0x6d, 0x65, 0x72, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x72, 0x6f, 0x77,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x79, 0x70, 0x65, 0x72, 0x6f, 0x77, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x72, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x72, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74,
	0x61, 0x72, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61,
	0x72, 0x6f, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x73, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x70, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65,
	0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x6a, 0x61, 0x63,
	0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61,
	0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x32, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x4d,
	0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x33, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x82, 0x02, 0x0a, 0x0c, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x04,
	0x73, 0x70, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x61, 0x75, 0x2e, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x70, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x04, 0x70, 0x72, 0x6f, 0x70, 0x22, 0xc5, 0x01,
	0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x45, 0x6e, 0x75, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x2a, 0x5b, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x41,
	0x59, 0x4f, 0x55, 0x54, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x4c, 0x41, 0x59, 0x4f, 0x55, 0x54, 0x5f, 0x56, 0x45, 0x52, 0x54, 0x49, 0x43, 0x41,
	0x4c, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x41, 0x59, 0x4f, 0x55, 0x54, 0x5f, 0x48, 0x4f,
	0x52, 0x49, 0x5a, 0x4f, 0x4e, 0x54, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x41,
	0x59, 0x4f, 0x55, 0x54, 0x5f, 0x49, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x10, 0x03, 0x2a, 0x42, 0x0a,
	0x04, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x50, 0x41, 0x4e, 0x5f, 0x44, 0x45,
	0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x50, 0x41, 0x4e, 0x5f,
	0x43, 0x52, 0x4f, 0x53, 0x53, 0x5f, 0x43, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x53, 0x50, 0x41, 0x4e, 0x5f, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x45, 0x4c, 0x4c, 0x10,
	0x02, 0x3a, 0x54, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x3a, 0x5a, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x68, 0x65, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x68, 0x65, 0x65,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x68,
	0x65, 0x65, 0x74, 0x3a, 0x4c, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x3a, 0x48, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x3a, 0x56, 0x0a, 0x06, 0x65,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x69, 0x6f, 0x2f, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x61, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61,
	0x75, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tableau_protobuf_tableau_proto_rawDescOnce sync.Once
	file_tableau_protobuf_tableau_proto_rawDescData = file_tableau_protobuf_tableau_proto_rawDesc
)

func file_tableau_protobuf_tableau_proto_rawDescGZIP() []byte {
	file_tableau_protobuf_tableau_proto_rawDescOnce.Do(func() {
		file_tableau_protobuf_tableau_proto_rawDescData = protoimpl.X.CompressGZIP(file_tableau_protobuf_tableau_proto_rawDescData)
	})
	return file_tableau_protobuf_tableau_proto_rawDescData
}

var file_tableau_protobuf_tableau_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tableau_protobuf_tableau_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tableau_protobuf_tableau_proto_goTypes = []interface{}{
	(Layout)(0),                           // 0: tableau.Layout
	(Span)(0),                             // 1: tableau.Span
	(*WorkbookOptions)(nil),               // 2: tableau.WorkbookOptions
	(*WorksheetOptions)(nil),              // 3: tableau.WorksheetOptions
	(*FieldOptions)(nil),                  // 4: tableau.FieldOptions
	(*FieldProp)(nil),                     // 5: tableau.FieldProp
	(*EnumOptions)(nil),                   // 6: tableau.EnumOptions
	(*EnumValueOptions)(nil),              // 7: tableau.EnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 10: google.protobuf.FieldOptions
	(*descriptorpb.EnumOptions)(nil),      // 11: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 12: google.protobuf.EnumValueOptions
}
var file_tableau_protobuf_tableau_proto_depIdxs = []int32{
	0,  // 0: tableau.FieldOptions.layout:type_name -> tableau.Layout
	1,  // 1: tableau.FieldOptions.span:type_name -> tableau.Span
	5,  // 2: tableau.FieldOptions.prop:type_name -> tableau.FieldProp
	8,  // 3: tableau.workbook:extendee -> google.protobuf.FileOptions
	9,  // 4: tableau.worksheet:extendee -> google.protobuf.MessageOptions
	10, // 5: tableau.field:extendee -> google.protobuf.FieldOptions
	11, // 6: tableau.enum:extendee -> google.protobuf.EnumOptions
	12, // 7: tableau.evalue:extendee -> google.protobuf.EnumValueOptions
	2,  // 8: tableau.workbook:type_name -> tableau.WorkbookOptions
	3,  // 9: tableau.worksheet:type_name -> tableau.WorksheetOptions
	4,  // 10: tableau.field:type_name -> tableau.FieldOptions
	6,  // 11: tableau.enum:type_name -> tableau.EnumOptions
	7,  // 12: tableau.evalue:type_name -> tableau.EnumValueOptions
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	8,  // [8:13] is the sub-list for extension type_name
	3,  // [3:8] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tableau_protobuf_tableau_proto_init() }
func file_tableau_protobuf_tableau_proto_init() {
	if File_tableau_protobuf_tableau_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tableau_protobuf_tableau_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkbookOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableau_protobuf_tableau_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorksheetOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableau_protobuf_tableau_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableau_protobuf_tableau_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldProp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableau_protobuf_tableau_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableau_protobuf_tableau_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumValueOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tableau_protobuf_tableau_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tableau_protobuf_tableau_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_tableau_protobuf_tableau_proto_goTypes,
		DependencyIndexes: file_tableau_protobuf_tableau_proto_depIdxs,
		EnumInfos:         file_tableau_protobuf_tableau_proto_enumTypes,
		MessageInfos:      file_tableau_protobuf_tableau_proto_msgTypes,
		ExtensionInfos:    file_tableau_protobuf_tableau_proto_extTypes,
	}.Build()
	File_tableau_protobuf_tableau_proto = out.File
	file_tableau_protobuf_tableau_proto_rawDesc = nil
	file_tableau_protobuf_tableau_proto_goTypes = nil
	file_tableau_protobuf_tableau_proto_depIdxs = nil
}
