name: Buf CI
on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Buf CI
        uses: bufbuild/buf-action@v1
        with:
          version: 1.69.0
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
