name: Lint

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.2.1

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1.50.0
        with:
          version: 1.67.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Buf Lint
        run: buf lint

      - name: Buf Generate and Check
        run: |
          buf generate
          if git diff --name-only | grep -q "\.go$"; then
            echo "Error: Generated Go files are not committed"
            git diff
            exit 1
          fi
