name: Lint

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.2.1
